# Generated by Django 4.0.3 on 2024-07-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0004_bloodrequest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
